- name: CONFIGURE DB CONNECTION SERVER
  hosts: db 
  become: yes
  tasks:
  - name: INSTALL MYSQL SERVER
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: START AND ENABLED MYSQL SERVER
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

# CHECK password setup exist or not

- name: CHECK DB CONNECTION
  community.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: db
    filter: version
  ignore_errors: 
  register: mysql_db_connection_output

#print the output

- name: Print the mysql db connection output
  ansible.builtin.debug:
    msg: "otuput: {{ mysql_db_connection_output }}"