- name: CONFIGURE DB CONNECTION SERVER
  hosts: db 
  become: yes
  vars_prompt:
  - name: mysql_password
    prompt: Enter MYSQL password
  tasks:
  - name: INSTALL MYSQL SERVER
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: START AND ENABLED MYSQL SERVER
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  # python dependencies for mysql connection server it is required

  - name: Python dependencies for mysql
    ansible.builtin.pip:
      name: 
      - PyMySQL
      - cryptography
      executable: pip3.9

  # CHECK password setup exist or not

  - name: CHECK DB CONNECTION
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_password }}"
      login_host: db
      filter: version
    ignore_errors: 
    register: mysql_db_connection_output

  #print the output

  - name: Print the mysql db connection output
    ansible.builtin.debug:
      msg: "otuput: {{ mysql_db_connection_output }}"

  # setup root password

  - name: SETUP ROOT password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_password }}"
    when: mysql_db_connection_output.failed is true

